swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction
      summary: View current month's transactions
      description: View current month's transactions of the user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "500":
          description: Internal Server Error
  /user/profile/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction
      summary: View one of transaction details
      description: Details of transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: id
          required: true
          description: Need of transaction's id
          type: integer
        - in: body
          name: body
          description: Details of transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionsId"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/DetailTransactionsResponse"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Transaction
      summary: User transaction's information
      description: API for updating a transaction's information by the user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: id
          required: true
          description: Need of transaction's id
          type: integer
        - in: body
          name: body
          required: true
          description: Update user current month's transactions
          schema:
            $ref: "#/definitions/TransactionsId"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/DetailTransactionsResponse"
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionsId:
    type: object
    properties:
      id:
        type: string
      category:
        type: string
        description: category
      notes:
        type: string
        description: notes
  TransactionsResponse:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
        description:
          type: string
        amount:
          type: number
        balance:
          type: number
  DetailTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          category:
            type: string
          notes:
            type: string
